- alias: Breezeway On
  hide_entity: True
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_door
      to: 'on'
    - platform: state
      entity_id: sensor.garage_door_contact
      to: 'open'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'    
      - condition: state
        entity_id: light.breezeway_lamp
        state: 'off'
  action: 
    service: homeassistant.turn_on
    entity_id: light.breezeway_lamp
- alias: Breezeway Doors Closed
  hide_entity: True
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_door
      from: 'on'
      to: 'off'
    - platform: state
      entity_id: sensor.garage_door_contact
      from: 'open'
      to: 'closed'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.breezeway_lamp
        state: 'on'
      - condition: state
        entity_id: sensor.garage_door_contact
        state: 'closed'
      - condition: state
        entity_id: binary_sensor.kitchen_door
        state: 'off'
  action: 
    - service: script.turn_off
      entity_id: script.timed_lamp_breezeway
    - service: script.timed_lamp_breezeway
