- alias: "Entrance On After Sunset"
  hide_entity: True
  trigger:
    - platform: sun
      event: sunset
  condition:      
    condition: state
    entity_id: light.entrance_lamp
    state: 'off'
  action: 
    service: scene.turn_on
    data:
      entity_id: scene.entrance_lamp_bright
- alias: 'Entrance Motion Trigger'
  hide_entity: True
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_motion
      to: 'off'
    - platform: state
      entity_id: binary_sensor.main_door
      to: 'on'
    - platform: time
      after: "21:00"
  condition:
    condition: and
    conditions:
      - condition: time          
        after: '21:00:00'       
      - condition: or
        conditions:
          - condition: sun
            after: sunset
          - condition: sun
            before: sunrise
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.entrance_lamp_nightlight
    - service: script.turn_off
      entity_id: script.timed_lamp_entrance
    - service: script.timed_lamp_entrance
