- alias: Keep Family room brightness in sync
  hide_entity: True
  trigger:
    platform: state
    entity_id: sensor.current_familyroom_brightness
  action:
    - service: light.turn_on
      data_template:
        entity_id: 
          - light.family_door_lamp
          - light.family_corner_lamp
        brightness: '{{ trigger.to_state.state | int }}'
- alias: Keep Family room brightness in sync off
  hide_entity: True
  trigger:
    platform: state
    entity_id: light.family_room_lights
    to: 'off'
  action:
    service: light.turn_off
    entity_id: group.family_room
- alias: 'Family Room Motion On Trigger'
  hide_entity: True
  trigger:
    platform: state
    entity_id: binary_sensor.family_room_motion
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: time          
        before: '22:00:00'       
      - condition: or
        conditions:
          - condition: sun
            after: sunset    
      - condition: or
        conditions:
        - condition: state
          entity_id: light.family_room_lights
          state: 'off'
        - condition: state
          entity_id: light.family_door_lamp
          state: 'off'
        - condition: state
          entity_id: light.family_corner_lamp
          state: 'off'
  action:
    service: light.turn_on
    entity_id: group.family_room
- alias: 'Family Room Motion Off Trigger'
  hide_entity: True
  trigger:
    platform: state
    entity_id: binary_sensor.family_room_motion
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: time          
        after: '22:00:00'       
      - condition: or
        conditions:
          - condition: sun
            after: sunset
          - condition: sun
            before: sunrise
      - condition: or
        conditions:
        - condition: state
          entity_id: light.family_room_lights
          state: 'on'
        - condition: state
          entity_id: light.family_door_lamp
          state: 'on'
        - condition: state
          entity_id: light.family_corner_lamp
          state: 'on'
  action:
    - service: script.turn_off
      entity_id: script.timed_lamps_familyroom
    - service: script.timed_lamps_familyroom