- alias: "Living Room On After Sunset"
  hide_entity: True
  trigger:
    - platform: sun
      event: sunset
      offset: '-00:30:00'
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: light.living_room_corner_light
      state: 'off'
    - condition: state
      entity_id: light.living_window_lamp
      state: 'off'
  action: 
    service: homeassistant.turn_on
    entity_id: 
      - light.living_room_corner_light
      - light.living_window_lamp
- alias: "Living Room Off Timer"
  # hide_entity: True
  trigger:
    platform: time
    after: "21:00:00"
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
      - condition: sun
        before: sunrise
  action:
    - service: script.turn_off
      entity_id: script.timed_lamps_livingroom
    - service: script.timed_lamps_livingroom
- alias: 'Living Room Motion Trigger'
  # hide_entity: True
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_motion
    from: 'on'
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: time          
        after: '21:00:00'       
      - condition: or
        conditions:
          - condition: sun
            after: sunset
          - condition: sun
            before: sunrise
      - condition: or
        conditions:
        - condition: state
          entity_id: light.living_room_corner_light
          state: 'on'
        - condition: state
          entity_id: light.living_window_lamp
          state: 'on'
  action:
    - service: script.turn_off
      entity_id: script.timed_lamps_livingroom
    - service: script.timed_lamps_livingroom
  