- alias: Turn on at Sunset
  hide_entity: True
  trigger:
    - platform: sun
      event: sunset
  action: 
    service: homeassistant.turn_on
    entity_id: 
      - light.front_door_lights
      - light.deck_back_light
      - light.deck_bbq_light
- alias: Turn off at Sunrise
  hide_entity: True
  trigger:
    - platform: sun
      event: sunrise
  action: 
    service: homeassistant.turn_off
    entity_id: 
      - light.front_door_lights
      - light.deck_back_light
      - light.deck_bbq_light
